//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVRClient.IVRServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupContract", Namespace="http://schemas.datacontract.org/2004/07/IVRService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GroupContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IVRClient.IVRServiceReference.PersonContract[] PersonsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IVRClient.IVRServiceReference.PersonContract[] Persons {
            get {
                return this.PersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsField, value) != true)) {
                    this.PersonsField = value;
                    this.RaisePropertyChanged("Persons");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonContract", Namespace="http://schemas.datacontract.org/2004/07/IVRService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PersonContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdayInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommunityInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobFamilyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReflectionInFamilyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReflectionInJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YearStartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthdayDate {
            get {
                return this.BirthdayDateField;
            }
            set {
                if ((this.BirthdayDateField.Equals(value) != true)) {
                    this.BirthdayDateField = value;
                    this.RaisePropertyChanged("BirthdayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthdayInfo {
            get {
                return this.BirthdayInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayInfoField, value) != true)) {
                    this.BirthdayInfoField = value;
                    this.RaisePropertyChanged("BirthdayInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommunityInfo {
            get {
                return this.CommunityInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunityInfoField, value) != true)) {
                    this.CommunityInfoField = value;
                    this.RaisePropertyChanged("CommunityInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Education {
            get {
                return this.EducationField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationField, value) != true)) {
                    this.EducationField = value;
                    this.RaisePropertyChanged("Education");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIO {
            get {
                return this.FIOField;
            }
            set {
                if ((object.ReferenceEquals(this.FIOField, value) != true)) {
                    this.FIOField = value;
                    this.RaisePropertyChanged("FIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Family {
            get {
                return this.FamilyField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyField, value) != true)) {
                    this.FamilyField = value;
                    this.RaisePropertyChanged("Family");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hobby {
            get {
                return this.HobbyField;
            }
            set {
                if ((object.ReferenceEquals(this.HobbyField, value) != true)) {
                    this.HobbyField = value;
                    this.RaisePropertyChanged("Hobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobFamily {
            get {
                return this.JobFamilyField;
            }
            set {
                if ((object.ReferenceEquals(this.JobFamilyField, value) != true)) {
                    this.JobFamilyField = value;
                    this.RaisePropertyChanged("JobFamily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presents {
            get {
                return this.PresentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentsField, value) != true)) {
                    this.PresentsField = value;
                    this.RaisePropertyChanged("Presents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReflectionInFamily {
            get {
                return this.ReflectionInFamilyField;
            }
            set {
                if ((object.ReferenceEquals(this.ReflectionInFamilyField, value) != true)) {
                    this.ReflectionInFamilyField = value;
                    this.RaisePropertyChanged("ReflectionInFamily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReflectionInJob {
            get {
                return this.ReflectionInJobField;
            }
            set {
                if ((object.ReferenceEquals(this.ReflectionInJobField, value) != true)) {
                    this.ReflectionInJobField = value;
                    this.RaisePropertyChanged("ReflectionInJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sport {
            get {
                return this.SportField;
            }
            set {
                if ((object.ReferenceEquals(this.SportField, value) != true)) {
                    this.SportField = value;
                    this.RaisePropertyChanged("Sport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string War {
            get {
                return this.WarField;
            }
            set {
                if ((object.ReferenceEquals(this.WarField, value) != true)) {
                    this.WarField = value;
                    this.RaisePropertyChanged("War");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YearStart {
            get {
                return this.YearStartField;
            }
            set {
                if ((this.YearStartField.Equals(value) != true)) {
                    this.YearStartField = value;
                    this.RaisePropertyChanged("YearStart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkContract", Namespace="http://schemas.datacontract.org/2004/07/IVRService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class WorkContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPersonInitiatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InputDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPerson {
            get {
                return this.IDPersonField;
            }
            set {
                if ((this.IDPersonField.Equals(value) != true)) {
                    this.IDPersonField = value;
                    this.RaisePropertyChanged("IDPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPersonInitiator {
            get {
                return this.IDPersonInitiatorField;
            }
            set {
                if ((this.IDPersonInitiatorField.Equals(value) != true)) {
                    this.IDPersonInitiatorField = value;
                    this.RaisePropertyChanged("IDPersonInitiator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InputDateTime {
            get {
                return this.InputDateTimeField;
            }
            set {
                if ((this.InputDateTimeField.Equals(value) != true)) {
                    this.InputDateTimeField = value;
                    this.RaisePropertyChanged("InputDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resolution {
            get {
                return this.ResolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolutionField, value) != true)) {
                    this.ResolutionField = value;
                    this.RaisePropertyChanged("Resolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkDescription {
            get {
                return this.WorkDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkDescriptionField, value) != true)) {
                    this.WorkDescriptionField = value;
                    this.RaisePropertyChanged("WorkDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PenaltyContract", Namespace="http://schemas.datacontract.org/2004/07/IVRService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PenaltyContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentDestroyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDDocumentInitiatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPenaltyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InputDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentDestroy {
            get {
                return this.DocumentDestroyField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDestroyField, value) != true)) {
                    this.DocumentDestroyField = value;
                    this.RaisePropertyChanged("DocumentDestroy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDDocumentInitiator {
            get {
                return this.IDDocumentInitiatorField;
            }
            set {
                if ((this.IDDocumentInitiatorField.Equals(value) != true)) {
                    this.IDDocumentInitiatorField = value;
                    this.RaisePropertyChanged("IDDocumentInitiator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPenaltyType {
            get {
                return this.IDPenaltyTypeField;
            }
            set {
                if ((this.IDPenaltyTypeField.Equals(value) != true)) {
                    this.IDPenaltyTypeField = value;
                    this.RaisePropertyChanged("IDPenaltyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPerson {
            get {
                return this.IDPersonField;
            }
            set {
                if ((this.IDPersonField.Equals(value) != true)) {
                    this.IDPersonField = value;
                    this.RaisePropertyChanged("IDPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InputDateTime {
            get {
                return this.InputDateTimeField;
            }
            set {
                if ((this.InputDateTimeField.Equals(value) != true)) {
                    this.InputDateTimeField = value;
                    this.RaisePropertyChanged("InputDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionContract", Namespace="http://schemas.datacontract.org/2004/07/IVRService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PromotionContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDDocumentInitiatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPromotionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InputDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDDocumentInitiator {
            get {
                return this.IDDocumentInitiatorField;
            }
            set {
                if ((this.IDDocumentInitiatorField.Equals(value) != true)) {
                    this.IDDocumentInitiatorField = value;
                    this.RaisePropertyChanged("IDDocumentInitiator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPerson {
            get {
                return this.IDPersonField;
            }
            set {
                if ((this.IDPersonField.Equals(value) != true)) {
                    this.IDPersonField = value;
                    this.RaisePropertyChanged("IDPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPromotionType {
            get {
                return this.IDPromotionTypeField;
            }
            set {
                if ((this.IDPromotionTypeField.Equals(value) != true)) {
                    this.IDPromotionTypeField = value;
                    this.RaisePropertyChanged("IDPromotionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InputDateTime {
            get {
                return this.InputDateTimeField;
            }
            set {
                if ((this.InputDateTimeField.Equals(value) != true)) {
                    this.InputDateTimeField = value;
                    this.RaisePropertyChanged("InputDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionTypeContract", Namespace="http://schemas.datacontract.org/2004/07/IVRService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PromotionTypeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PenaltyTypeContract", Namespace="http://schemas.datacontract.org/2004/07/IVRService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PenaltyTypeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVRServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroupsWithPersons", ReplyAction="http://tempuri.org/IService/GetGroupsWithPersonsResponse")]
        IVRClient.IVRServiceReference.GroupContract[] GetGroupsWithPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroupsWithPersons", ReplyAction="http://tempuri.org/IService/GetGroupsWithPersonsResponse")]
        System.Threading.Tasks.Task<IVRClient.IVRServiceReference.GroupContract[]> GetGroupsWithPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorks", ReplyAction="http://tempuri.org/IService/GetWorksResponse")]
        IVRClient.IVRServiceReference.WorkContract[] GetWorks(int IDPerson, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorks", ReplyAction="http://tempuri.org/IService/GetWorksResponse")]
        System.Threading.Tasks.Task<IVRClient.IVRServiceReference.WorkContract[]> GetWorksAsync(int IDPerson, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPenalties", ReplyAction="http://tempuri.org/IService/GetPenaltiesResponse")]
        IVRClient.IVRServiceReference.PenaltyContract[] GetPenalties(int IDPerson, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPenalties", ReplyAction="http://tempuri.org/IService/GetPenaltiesResponse")]
        System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PenaltyContract[]> GetPenaltiesAsync(int IDPerson, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPromotions", ReplyAction="http://tempuri.org/IService/GetPromotionsResponse")]
        IVRClient.IVRServiceReference.PromotionContract[] GetPromotions(int IDPerson, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPromotions", ReplyAction="http://tempuri.org/IService/GetPromotionsResponse")]
        System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PromotionContract[]> GetPromotionsAsync(int IDPerson, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPromotionsType", ReplyAction="http://tempuri.org/IService/GetPromotionsTypeResponse")]
        IVRClient.IVRServiceReference.PromotionTypeContract[] GetPromotionsType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPromotionsType", ReplyAction="http://tempuri.org/IService/GetPromotionsTypeResponse")]
        System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PromotionTypeContract[]> GetPromotionsTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPenaltiesType", ReplyAction="http://tempuri.org/IService/GetPenaltiesTypeResponse")]
        IVRClient.IVRServiceReference.PenaltyTypeContract[] GetPenaltiesType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPenaltiesType", ReplyAction="http://tempuri.org/IService/GetPenaltiesTypeResponse")]
        System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PenaltyTypeContract[]> GetPenaltiesTypeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : IVRClient.IVRServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<IVRClient.IVRServiceReference.IService>, IVRClient.IVRServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IVRClient.IVRServiceReference.GroupContract[] GetGroupsWithPersons() {
            return base.Channel.GetGroupsWithPersons();
        }
        
        public System.Threading.Tasks.Task<IVRClient.IVRServiceReference.GroupContract[]> GetGroupsWithPersonsAsync() {
            return base.Channel.GetGroupsWithPersonsAsync();
        }
        
        public IVRClient.IVRServiceReference.WorkContract[] GetWorks(int IDPerson, int year) {
            return base.Channel.GetWorks(IDPerson, year);
        }
        
        public System.Threading.Tasks.Task<IVRClient.IVRServiceReference.WorkContract[]> GetWorksAsync(int IDPerson, int year) {
            return base.Channel.GetWorksAsync(IDPerson, year);
        }
        
        public IVRClient.IVRServiceReference.PenaltyContract[] GetPenalties(int IDPerson, int year) {
            return base.Channel.GetPenalties(IDPerson, year);
        }
        
        public System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PenaltyContract[]> GetPenaltiesAsync(int IDPerson, int year) {
            return base.Channel.GetPenaltiesAsync(IDPerson, year);
        }
        
        public IVRClient.IVRServiceReference.PromotionContract[] GetPromotions(int IDPerson, int year) {
            return base.Channel.GetPromotions(IDPerson, year);
        }
        
        public System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PromotionContract[]> GetPromotionsAsync(int IDPerson, int year) {
            return base.Channel.GetPromotionsAsync(IDPerson, year);
        }
        
        public IVRClient.IVRServiceReference.PromotionTypeContract[] GetPromotionsType() {
            return base.Channel.GetPromotionsType();
        }
        
        public System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PromotionTypeContract[]> GetPromotionsTypeAsync() {
            return base.Channel.GetPromotionsTypeAsync();
        }
        
        public IVRClient.IVRServiceReference.PenaltyTypeContract[] GetPenaltiesType() {
            return base.Channel.GetPenaltiesType();
        }
        
        public System.Threading.Tasks.Task<IVRClient.IVRServiceReference.PenaltyTypeContract[]> GetPenaltiesTypeAsync() {
            return base.Channel.GetPenaltiesTypeAsync();
        }
    }
}
