//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime InputDateTime { get; set; }
        public string Document { get; set; }
        public int IDDocumentInitiator { get; set; }
        public int IDPenaltyType { get; set; }
        public string Description { get; set; }
        public string DocumentDestroy { get; set; }
        public int IDPerson { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual PenaltyType PenaltyType { get; set; }
        public virtual Person Person { get; set; }
    }
}
