//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRank
    {
        public int IDPerson { get; set; }
        public int IDRank { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
