//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime InputDateTime { get; set; }
        public int IDPerson { get; set; }
        public string WorkDescription { get; set; }
        public string Resolution { get; set; }
        public string PersonInitiator { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
